# Generated by Django 6.1.1 on 2026-09-21 23:36

import django.db.models.deletion
import scolarite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Exemple : 2026-2027', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False, help_text="Une seule année scolaire active à la fois — c'est elle qui est proposée par défaut.")),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple : 3ème année A', max_length=60)),
                ('cycle', models.CharField(choices=[('1er_cycle', '1er cycle (1ère à 6ème année)'), ('2eme_cycle', '2ème cycle (7ème à 9ème année)')], max_length=20)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='scolarite.anneescolaire')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['annee_scolaire', 'cycle', 'nom'],
                'unique_together': {('nom', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='EcheancierFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_inscription', models.PositiveIntegerField(validators=[scolarite.models.valider_multiple_de_5000])),
                ('montant_tranche_1', models.PositiveIntegerField(validators=[scolarite.models.valider_multiple_de_5000])),
                ('montant_tranche_2', models.PositiveIntegerField(validators=[scolarite.models.valider_multiple_de_5000])),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='scolarite.classe')),
            ],
            options={
                'verbose_name': 'échéancier de frais',
                'verbose_name_plural': 'échéanciers de frais',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(blank=True, help_text='Laisser vide si professeur titulaire.', max_length=100)),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='scolarite.classe')),
            ],
            options={
                'verbose_name': "affectation d'enseignant",
                'verbose_name_plural': "affectations d'enseignants",
                'unique_together': {('enseignant', 'classe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('admis', 'Admis (année suivante)'), ('redouble', 'Redouble'), ('transfere', 'Transféré / parti')], default='en_cours', max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('eleve', 'classe')},
            },
        ),
    ]
