# Generated by Django 6.1.1 on 2026-09-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0004_generer_slugs_manquants'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annees_scolaires', to='etablissement.etablissement'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='est_active',
            field=models.BooleanField(default=False, help_text='Une seule année scolaire active à la fois par établissement.'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='libelle',
            field=models.CharField(help_text='Exemple : 2026-2027', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('etablissement', 'libelle')},
        ),
    ]
