# Generated by Django 6.1.1 on 2026-09-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0003_rattacher_annees_existantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classe_suivante',
            field=models.ForeignKey(blank=True, help_text="Classe vers laquelle les élèves admis de cette classe sont promus l'année suivante. Mémorisée pour ne pas avoir à la ressaisir chaque année.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_precedentes', to='scolarite.classe'),
        ),
    ]
