# Generated by Django 6.1.1 on 2026-09-24 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0005_alter_etablissement_logo"),
        ("scolarite", "0004_classe_classe_suivante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anneescolaire",
            name="est_archivee",
            field=models.BooleanField(
                default=False,
                help_text="Une année archivée reste consultable mais ne reçoit plus de nouvelles écritures.",
            ),
        ),
        migrations.CreateModel(
            name="AideScolarite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_aide",
                    models.CharField(
                        choices=[
                            ("bourse", "Bourse"),
                            ("reduction", "Réduction"),
                            ("exoneration", "Exonération"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.PositiveIntegerField(default=0)),
                ("pourcentage", models.PositiveSmallIntegerField(default=0)),
                ("motif", models.CharField(max_length=255)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "accordee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aides_accordees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aides_scolarite",
                        to="scolarite.inscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransfertEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_libelle", models.CharField(blank=True, max_length=255)),
                ("date_transfert", models.DateField()),
                ("motif", models.CharField(max_length=255)),
                ("justificatif", models.FileField(blank=True, upload_to="transferts/")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_enregistres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_recus",
                        to="etablissement.etablissement",
                    ),
                ),
                (
                    "inscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfert",
                        to="scolarite.inscription",
                    ),
                ),
            ],
        ),
    ]
