# Generated by Django 6.1.1 on 2026-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0005_anneescolaire_est_archivee_aidescolarite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echeancierfrais",
            name="montant_inscription",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="echeancierfrais",
            name="montant_tranche_1",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="echeancierfrais",
            name="montant_tranche_2",
            field=models.PositiveIntegerField(),
        ),
    ]
