# Generated by Django 6.1.1 on 2026-09-24 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0006_alter_echeancierfrais_montant_inscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affectation",
            name="coefficient",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Poids de cette matière dans le calcul de la moyenne du bulletin. 1 par défaut (toutes les matières comptent également) ; augmentez pour une matière à plus fort coefficient (ex. Mathématiques, Français).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
