# Generated by Django 6.1.1 on 2026-10-02 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0007_affectation_coefficient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[("attestation_scolarite", "Attestation de scolarité")],
                        max_length=30,
                    ),
                ),
                (
                    "jeton",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_verifiables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications_document",
                        to="scolarite.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "document vérifiable",
                "verbose_name_plural": "documents vérifiables",
                "ordering": ["-cree_le"],
            },
        ),
    ]
