# Generated by Django 6.1.1 on 2026-10-02 18:45

import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0008_verificationdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferteleve",
            name="justificatif",
            field=models.FileField(
                blank=True,
                upload_to="transferts/",
                validators=[
                    comptes.validators.valider_taille_fichier_10mo,
                    comptes.validators.valider_extension_document,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
