# Generated by Django 6.1.1 on 2026-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0009_alter_transferteleve_justificatif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classe",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("1er_cycle", "1er cycle (1ère à 6ème année)"),
                    ("2eme_cycle", "2ème cycle (7ème à 9ème année)"),
                    ("lycee", "Lycée (10ème à 12ème année)"),
                ],
                max_length=20,
            ),
        ),
    ]
