# Generated by Django 6.1.1 on 2026-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0010_alter_classe_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="serie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tse", "Sciences Exactes (TSE)"),
                    ("tsexp", "Sciences Expérimentales (TSExp)"),
                    ("tseco", "Sciences Économiques (TSEco)"),
                    ("tss", "Sciences Sociales (TSS)"),
                    ("tll", "Langues et Littérature (TLL)"),
                    ("tal", "Arts et Lettres (TAL)"),
                ],
                help_text="Uniquement pour une classe de 11ème ou 12ème année (lycée) - laisser vide sinon.",
                max_length=20,
                verbose_name="série",
            ),
        ),
    ]
