# Generated by Django 6.1.1 on 2026-10-04 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0011_classe_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="affectation",
            name="poids_bonus",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Poids du bonus dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="poids_devoirs",
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text="Poids des devoirs dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="poids_interrogations",
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text="Poids des interrogations dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
