# Generated by Django 6.1.1 on 2026-10-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scolarite",
            "0012_affectation_poids_bonus_affectation_poids_devoirs_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentEnAttente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        limit_choices_to={"role": "eleve"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents_en_attente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "parent en attente",
                "verbose_name_plural": "parents en attente",
                "ordering": ["-cree_le"],
                "unique_together": {("eleve", "email")},
            },
        ),
    ]
