# Generated by Django 6.1.1 on 2026-10-04 19:21

import django.core.validators
from django.db import migrations, models


def reinitialiser_poids_existants(apps, schema_editor):
    """
    Les affectations créées avant cette migration portent déjà
    poids_devoirs=40/poids_interrogations=40/poids_bonus=20 (introduits dans
    la migration précédente, sans poids_composition) : ajouter
    poids_composition=50 par défaut ferait totaliser 150%, faussant les
    proportions voulues plutôt que de simplement les recalculer sur 100.
    Remet toutes les affectations existantes aux nouveaux poids par défaut
    (50/25/15/10, alignés sur la pratique malienne où la composition
    trimestrielle domine) - aucune ne peut avoir été personnalisée
    manuellement avant cette migration, le champ n'existant pas encore.
    """
    Affectation = apps.get_model("scolarite", "Affectation")
    Affectation.objects.update(
        poids_composition=50, poids_devoirs=25, poids_interrogations=15, poids_bonus=10,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0013_parentenattente"),
    ]

    operations = [
        migrations.AddField(
            model_name="affectation",
            name="poids_composition",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Poids de la composition trimestrielle dans la note finale (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="poids_bonus",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Poids du bonus dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="poids_devoirs",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Poids des devoirs dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="poids_interrogations",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Poids des interrogations dans la note finale du trimestre (%).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.RunPython(reinitialiser_poids_existants, migrations.RunPython.noop),
    ]
