# Generated by Django 6.1.1 on 2026-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0014_affectation_poids_composition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classe",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("1er_cycle", "1er cycle"),
                    ("2eme_cycle", "2ème cycle"),
                    ("lycee", "Lycée"),
                ],
                max_length=20,
            ),
        ),
    ]
