# Generated by Django 6.1.1 on 2026-10-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0015_alter_classe_cycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affectation",
            name="poids_bonus",
        ),
        migrations.RemoveField(
            model_name="affectation",
            name="poids_composition",
        ),
        migrations.RemoveField(
            model_name="affectation",
            name="poids_devoirs",
        ),
        migrations.RemoveField(
            model_name="affectation",
            name="poids_interrogations",
        ),
    ]
