# Generated by Django 6.1.1 on 2026-10-05 17:17 (écrite à la main - voir migrer_vers_periodicite)

from django.db import migrations, models


def migrer_vers_periodicite(apps, schema_editor):
    """
    Les échéanciers existants ont exactement deux tranches post-inscription
    (montant_tranche_1 + montant_tranche_2), ce qui ne correspond à aucune
    des nouvelles périodicités (mensuel : 9 ou 10 versements ; trimestriel :
    3 ; annuel : 1). Pour ne rien changer au montant annuel déjà dû par les
    élèves déjà inscrits (donc à aucun solde déjà calculé), les deux
    tranches sont fusionnées en un versement annuel unique - l'école peut
    ensuite repasser au mensuel ou au trimestriel pour ses prochaines
    classes si elle le souhaite.
    """
    EcheancierFrais = apps.get_model("scolarite", "EcheancierFrais")
    for echeancier in EcheancierFrais.objects.all():
        echeancier.montant_periode = echeancier.montant_tranche_1 + echeancier.montant_tranche_2
        echeancier.periodicite = "annuel"
        echeancier.nombre_versements = 1
        echeancier.save(update_fields=["montant_periode", "periodicite", "nombre_versements"])


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0016_remove_affectation_poids_bonus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="echeancierfrais",
            name="montant_periode",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Montant par mois, par trimestre ou pour l'année selon la périodicité choisie.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="echeancierfrais",
            name="periodicite",
            field=models.CharField(
                choices=[("mensuel", "Mensuel"), ("trimestriel", "Trimestriel"), ("annuel", "Annuel")],
                default="trimestriel", max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="echeancierfrais",
            name="nombre_versements",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Nombre de versements (hors inscription) sur l'année scolaire : 9 ou 10 pour le "
                           "mensuel ; fixé automatiquement à 3 pour le trimestriel et 1 pour l'annuel.",
            ),
        ),
        migrations.RunPython(migrer_vers_periodicite, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="echeancierfrais",
            name="montant_tranche_1",
        ),
        migrations.RemoveField(
            model_name="echeancierfrais",
            name="montant_tranche_2",
        ),
    ]
