# Generated by Django 6.1.1 on 2026-10-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0017_echeancierfrais_periodicite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("admis", "Admis (année suivante)"),
                    ("redouble", "Redouble"),
                    ("transfere", "Transféré / parti"),
                    ("abandon", "Abandon"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Abandon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_abandon", models.DateField()),
                ("motif", models.CharField(max_length=255)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abandons_enregistres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abandon",
                        to="scolarite.inscription",
                    ),
                ),
            ],
        ),
    ]
