# Generated by Django 6.1.1 on 2026-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0018_alter_inscription_statut_abandon"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="filiere_professionnelle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cap", "CAP - cycle court (2 ans)"),
                    ("bt", "BT - cycle long (4 ans)"),
                ],
                help_text="Uniquement pour une classe du cycle Enseignement professionnel - laisser vide sinon. Le métier exact (électricité, couture...) se précise dans le nom de la classe.",
                max_length=20,
                verbose_name="filière",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("1er_cycle", "1er cycle"),
                    ("2eme_cycle", "2ème cycle"),
                    ("lycee", "Lycée"),
                    ("professionnel", "Enseignement professionnel"),
                ],
                max_length=20,
            ),
        ),
    ]
