# Generated by Django 6.1.1 on 2026-10-08 22:51

import comptes.validators
import scolarite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scolarite", "0019_classe_filiere_professionnelle_alter_classe_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferteleve",
            name="justificatif",
            field=models.FileField(
                blank=True,
                upload_to=scolarite.models.chemin_upload_transfert,
                validators=[
                    comptes.validators.valider_taille_fichier_10mo,
                    comptes.validators.valider_extension_document,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
