# Generated by Django 6.1.1 on 2026-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon établissement', help_text="Nom affiché partout dans l'application (barre latérale, emails, connexion).", max_length=200)),
                ('devise', models.CharField(blank=True, help_text='Devise ou slogan affiché sous le nom (facultatif).', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text="Logo affiché dans la barre latérale et sur la page de connexion. Si aucun logo n'est fourni, l'initiale du nom est utilisée à la place.", null=True, upload_to='etablissement/')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissement',
            },
        ),
    ]
