# Generated by Django 6.1.1 on 2026-09-22 09:42

import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo affiché dans la barre latérale et sur la page de connexion. Si aucun logo n'est fourni, l'initiale du nom est utilisée à la place. Taille maximale : 2 Mo.", null=True, upload_to='etablissement/', validators=[comptes.validators.valider_taille_image_2mo]),
        ),
    ]
