# Generated by Django 6.1.1 on 2026-09-23 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_alter_etablissement_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['nom'], 'verbose_name': 'établissement', 'verbose_name_plural': 'établissements'},
        ),
        migrations.AddField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True, help_text='Désactiver bloque la connexion de tous les comptes de cet établissement, sans supprimer ni modifier leurs comptes individuellement.', verbose_name='établissement actif'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='cree_le',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='visible_dans_annuaire',
            field=models.BooleanField(default=True, help_text="Si désactivé, cet établissement n'apparaît pas sur la page d'accueil publique (les comptes existants peuvent toujours s'y connecter via un lien direct).", verbose_name="visible dans l'annuaire public"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(help_text="Nom affiché partout dans l'application (barre latérale, emails, connexion).", max_length=200),
        ),
    ]
