# Generated by Django 6.1.1 on 2026-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0005_alter_etablissement_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="code_devise",
            field=models.CharField(
                default="FCFA",
                help_text="Code ou symbole monétaire affiché sur les montants (paiements, salaires, bulletins financiers, reçus). Exemples : FCFA, EUR, USD.",
                max_length=10,
                verbose_name="monnaie",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="pas_montant",
            field=models.PositiveIntegerField(
                default=5000,
                help_text="Les frais de scolarité (inscription, tranches) doivent être saisis par multiple de ce montant. 5000 correspond à la plus petite coupure courante en FCFA ; ajustez pour une autre monnaie.",
                verbose_name="pas de saisie des frais",
            ),
        ),
    ]
