# Generated by Django 6.1.1 on 2026-10-07 13:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0007_etablissement_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="taux_amo_employeur",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.5"),
                help_text="Pourcentage du salaire brut à la charge de l'établissement au titre de l'AMO (information uniquement, n'affecte pas le net payé à l'employé).",
                max_digits=5,
                verbose_name="taux AMO (part employeur)",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="taux_amo_salarie",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.06"),
                help_text="Pourcentage du salaire brut retenu sur le bulletin de paie au titre de l'AMO (CANAM).",
                max_digits=5,
                verbose_name="taux AMO (part salarié)",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="taux_inps_employeur",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.0"),
                help_text="Pourcentage du salaire brut à la charge de l'établissement (information uniquement, n'affecte pas le net payé à l'employé) - varie de 18,9 % à 21,9 % selon la classe de risque ATMP, à ajuster selon votre situation réelle.",
                max_digits=5,
                verbose_name="taux INPS (part employeur)",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="taux_inps_salarie",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.6"),
                help_text="Pourcentage du salaire brut retenu sur le bulletin de paie au titre de l'INPS.",
                max_digits=5,
                verbose_name="taux INPS (part salarié)",
            ),
        ),
    ]
