# Generated by Django 6.1.1 on 2026-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0008_etablissement_taux_amo_employeur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="inclut_professionnel",
            field=models.BooleanField(
                default=False,
                help_text="Réglage indépendant de la formule ci-dessus : l'enseignement professionnel est une branche parallèle au Lycée (accessible après le DEF), pas une suite du 1er/2ème cycle - un établissement peut donc le cumuler avec n'importe quelle formule. Modifiable uniquement depuis l'espace plateforme, comme la formule.",
                verbose_name="inclut l'enseignement professionnel (CAP/BT)",
            ),
        ),
    ]
