# Generated by Django 6.1.1 on 2026-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0009_etablissement_inclut_professionnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="plan",
            field=models.CharField(
                choices=[
                    ("premier_cycle", "1er cycle"),
                    ("premier_et_deuxieme_cycle", "1er et 2ème cycle"),
                    ("tous_cycles", "Tous les cycles (1er, 2ème, Lycée)"),
                    ("lycee_seul", "Lycée seul"),
                    ("professionnel_seul", "Enseignement professionnel seul"),
                ],
                default="tous_cycles",
                help_text="Cycles couverts par l'abonnement - restreint les cycles de classe créables et les rôles de direction de cycle attribuables. Modifiable uniquement depuis l'espace plateforme, jamais par l'établissement lui-même.",
                max_length=30,
                verbose_name="formule d'abonnement",
            ),
        ),
    ]
