# Generated by Django 6.1.1 on 2026-10-08 22:51

import comptes.validators
import etablissement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0010_formules_lycee_et_professionnel_seuls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo affiché dans la barre latérale et sur la page de connexion. Si aucun logo n'est fourni, l'initiale du nom est utilisée à la place. Taille maximale : 2 Mo.",
                null=True,
                upload_to=etablissement.models.chemin_upload_logo,
                validators=[
                    comptes.validators.valider_taille_image_2mo,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
