# Generated by Django 6.1.1 on 2026-09-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='scolarite.affectation')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='scolarite.classe')),
            ],
            options={
                'verbose_name': "créneau d'emploi du temps",
                'verbose_name_plural': "créneaux d'emploi du temps",
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('saisie_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='scolarite.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
                'ordering': ['-date_absence'],
                'unique_together': {('eleve', 'date_absence')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('trimestre_1', '1er trimestre'), ('trimestre_2', '2ème trimestre'), ('trimestre_3', '3ème trimestre')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('saisie_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='scolarite.affectation')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-modifie_le'],
                'unique_together': {('eleve', 'affectation', 'trimestre')},
            },
        ),
    ]
