# Generated by Django 6.1.1 on 2026-09-24 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0005_alter_etablissement_logo"),
        ("pedagogie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ancienne_valeur",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("modifiee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "modifiee_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="pedagogie.note",
                    ),
                ),
            ],
            options={
                "ordering": ["-modifiee_le"],
            },
        ),
        migrations.CreateModel(
            name="PresencePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "En retard"),
                            ("conge", "Congé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presences_personnel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presences_personnel",
                        to="etablissement.etablissement",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presences_saisies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employe", "date"),
                        name="presence_personnel_unique_jour",
                    )
                ],
            },
        ),
    ]
