# Generated by Django 6.1.1 on 2026-09-24 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogie", "0002_notehistorique_presencepersonnel"),
        ("scolarite", "0005_anneescolaire_est_archivee_aidescolarite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationBulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeton",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins_verifiables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications_bulletin",
                        to="scolarite.inscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
    ]
