# Generated by Django 6.1.1 on 2026-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogie", "0005_alter_evaluation_type_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_classe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sur 20 (contrôle continu).",
                max_digits=4,
                null=True,
                verbose_name="note de classe",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="note_composition",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sur 40 (examen trimestriel - compte double dans la moyenne).",
                max_digits=5,
                null=True,
                verbose_name="note de composition",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="valeur",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Moyenne de la matière, sur 20 - calculée automatiquement.",
                max_digits=4,
            ),
        ),
        migrations.DeleteModel(
            name="Evaluation",
        ),
    ]
