# Generated by Django 6.1.1 on 2026-09-22 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone_contact', models.CharField(blank=True, help_text="Téléphone d'un parent ou tuteur.", max_length=20)),
                ('date_test', models.DateField(default=django.utils.timezone.localdate)),
                ('note_test', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('decision', models.CharField(choices=[('en_attente', 'En attente'), ('admis', 'Admis'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('classe_visee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='scolarite.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_enregistres', to=settings.AUTH_USER_MODEL)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_candidats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidat',
                'verbose_name_plural': 'candidats',
                'ordering': ['-date_test'],
            },
        ),
    ]
