# Generated by Django 6.1.1 on 2026-09-22 09:42

import bibliotheque.models
import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=bibliotheque.models.chemin_upload_document, validators=[comptes.validators.valider_taille_fichier_10mo]),
        ),
    ]
