# Generated by Django 6.1.1 on 2026-09-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_alter_document_fichier'),
        ('etablissement', '0004_generer_slugs_manquants'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='etablissement.etablissement'),
        ),
    ]
