# Generated by Django 6.1.1 on 2026-09-23 17:44

import bibliotheque.models
import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_rattacher_documents_existants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=bibliotheque.models.chemin_upload_document, validators=[comptes.validators.valider_taille_fichier_10mo, comptes.validators.valider_extension_document]),
        ),
    ]
