# Generated by Django 6.1.1 on 2026-09-24 11:03

import bibliotheque.models
import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0005_alter_document_fichier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                upload_to=bibliotheque.models.chemin_upload_document,
                validators=[
                    comptes.validators.valider_taille_fichier_10mo,
                    comptes.validators.valider_extension_document,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
