# Generated by Django 6.1.1 on 2026-09-22 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='annonces/')),
                ('portee', models.CharField(choices=[('toute_ecole', "Toute l'école"), ('ma_classe', 'Une classe précise')], max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('classe_ciblee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='scolarite.classe')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
