# Generated by Django 6.1.1 on 2026-09-22 09:42

import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='annonces/', validators=[comptes.validators.valider_taille_fichier_10mo]),
        ),
    ]
