# Generated by Django 6.1.1 on 2026-09-23 17:44

import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_rattacher_annonces_existantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='annonces/', validators=[comptes.validators.valider_taille_fichier_10mo, comptes.validators.valider_extension_document]),
        ),
    ]
