# Generated by Django 6.1.1 on 2026-09-24 11:03

import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0005_alter_annonce_piece_jointe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="piece_jointe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="annonces/",
                validators=[
                    comptes.validators.valider_taille_fichier_10mo,
                    comptes.validators.valider_extension_document,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
