# Generated by Django 6.1.1 on 2026-09-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0006_alter_annonce_piece_jointe"),
        ("etablissement", "0006_etablissement_code_devise_etablissement_pas_montant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField(max_length=2000)),
                ("envoye_le", models.DateTimeField(auto_now_add=True)),
                ("lu_le", models.DateTimeField(blank=True, null=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        limit_choices_to={"role": "eleve"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_le_concernant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="etablissement.etablissement",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_envoyes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ["envoye_le"],
            },
        ),
    ]
