# Generated by Django 6.1.1 on 2026-10-08 22:51

import communication.models
import comptes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0007_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="piece_jointe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=communication.models.chemin_upload_annonce,
                validators=[
                    comptes.validators.valider_taille_fichier_10mo,
                    comptes.validators.valider_extension_document,
                    comptes.validators.valider_contenu_fichier,
                ],
            ),
        ),
    ]
