# Generated by Django 6.1.1 on 2026-09-21 23:26

import comptes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('role', models.CharField(choices=[('developpeur', 'Développeur'), ('fondateur', 'Fondateur'), ('administrateur_general', 'Administrateur général'), ('directeur_1er_cycle', 'Directeur du 1er cycle'), ('directeur_2eme_cycle', 'Directeur du 2ème cycle'), ('super_administrateur', 'Super administrateur'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('responsable_pedagogique', 'Responsable pédagogique'), ('bibliothecaire', 'Bibliothécaire'), ('personnel', 'Personnel (générique)'), ('enseignant', 'Enseignant'), ('parent', 'Parent'), ('eleve', 'Élève')], max_length=40, verbose_name='rôle')),
                ('statut', models.CharField(choices=[('en_attente_verification_email', "En attente de vérification de l'email"), ('en_attente_validation', 'En attente de validation (secrétariat/direction)'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('desactive', 'Désactivé')], default='en_attente_verification_email', max_length=40, verbose_name='statut du compte')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='téléphone')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='profession')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='matricule')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('email_verifie', models.BooleanField(default=False, verbose_name='email vérifié')),
                ('tentatives_connexion_echouees', models.PositiveSmallIntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin technique')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parents_lies', models.ManyToManyField(blank=True, limit_choices_to={'role': 'parent'}, related_name='enfants_lies', to=settings.AUTH_USER_MODEL, verbose_name='parent(s) lié(s)')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
            managers=[
                ('objects', comptes.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeVerificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(default=comptes.models._expiration_par_defaut)),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de vérification email',
                'verbose_name_plural': 'codes de vérification email',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('cible', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-horodatage'],
            },
        ),
    ]
