# Generated by Django 6.1.1 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Utilisé pour les statistiques par sexe (effectifs, taux de réussite).', max_length=1, null=True, verbose_name='sexe'),
        ),
    ]
