# Generated by Django 6.1.1 on 2026-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverificationemail',
            name='tentatives_echouees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
