# Generated by Django 6.1.1 on 2026-09-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_codeverificationemail_tentatives_echouees'),
        ('etablissement', '0003_alter_etablissement_options_etablissement_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, help_text='Établissement auquel ce compte appartient. Détermine les données (élèves, classes, finances...) visibles pour ce compte.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='etablissement.etablissement'),
        ),
    ]
