# Generated by Django 6.1.1 on 2026-09-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_rattacher_comptes_existants'),
        ('etablissement', '0004_generer_slugs_manquants'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_audit', to='etablissement.etablissement'),
        ),
    ]
