# Generated by Django 6.1.1 on 2026-09-24 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0006_journalaudit_etablissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=255)),
                ("contenu", models.TextField()),
                ("expediteur", models.EmailField(max_length=254)),
                ("destinataires", models.JSONField(default=list)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("envoye_le", models.DateTimeField(blank=True, null=True)),
                ("tentatives", models.PositiveSmallIntegerField(default=0)),
                (
                    "prochaine_tentative",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("derniere_erreur", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["cree_le"],
            },
        ),
    ]
