# Generated by Django 6.1.1 on 2026-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailoutbox",
            name="verrouille_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
