# Generated by Django 6.1.1 on 2026-09-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0009_emailoutbox_verrouille_le"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="deux_facteurs_actif",
            field=models.BooleanField(default=False, verbose_name="2FA activée"),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="totp_secret",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
