# Generated by Django 6.1.1 on 2026-09-29 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0012_reessayer_premier_developpeur"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSecours2FA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hache", models.CharField(max_length=128)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("utilise", models.BooleanField(default=False)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes_secours_2fa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "code de secours 2FA",
                "verbose_name_plural": "codes de secours 2FA",
            },
        ),
    ]
