# Generated by Django 6.1.1 on 2026-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0013_codesecours2fa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("developpeur", "Développeur"),
                    ("fondateur", "Fondateur"),
                    ("administrateur_general", "Administrateur général"),
                    ("directeur_1er_cycle", "Directeur du 1er cycle"),
                    ("directeur_2eme_cycle", "Directeur du 2ème cycle"),
                    ("directeur_lycee", "Directeur du lycée"),
                    ("super_administrateur", "Super administrateur"),
                    ("secretaire", "Secrétaire"),
                    ("comptable", "Comptable"),
                    ("responsable_pedagogique", "Responsable pédagogique"),
                    ("bibliothecaire", "Bibliothécaire"),
                    ("personnel", "Personnel (générique)"),
                    ("enseignant", "Enseignant"),
                    ("parent", "Parent"),
                    ("eleve", "Élève"),
                ],
                max_length=40,
                verbose_name="rôle",
            ),
        ),
    ]
