# Generated by Django 6.1.1 on 2026-10-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0015_alter_utilisateur_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="doit_changer_mot_de_passe",
            field=models.BooleanField(
                default=False, verbose_name="doit changer son mot de passe"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="mot_de_passe_provisoire_expire_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
