# Generated by Django 6.1.1 on 2026-09-21 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.CharField(choices=[('inscription', 'Inscription'), ('tranche_1', 'Tranche 1'), ('tranche_2', 'Tranche 2')], max_length=20)),
                ('montant', models.PositiveIntegerField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('est_supprime', models.BooleanField(default=False)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='scolarite.inscription')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_supprimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format AAAA-MM, exemple : 2026-10', max_length=7)),
                ('montant', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('est_supprime', models.BooleanField(default=False)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaires', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaires_enregistres', to=settings.AUTH_USER_MODEL)),
                ('paye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaires_payes', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaires_supprimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'salaire',
                'verbose_name_plural': 'salaires',
                'ordering': ['-periode'],
                'unique_together': {('employe', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('annule', models.BooleanField(default=False)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_annules', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvement_caisse', to='finances.paiement')),
                ('salaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvement_caisse', to='finances.salaire')),
            ],
            options={
                'verbose_name': 'mouvement de caisse',
                'verbose_name_plural': 'mouvements de caisse',
                'ordering': ['-date_mouvement'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('paiement__isnull', False), ('salaire__isnull', True)), models.Q(('paiement__isnull', True), ('salaire__isnull', False)), _connector='OR'), name='mouvement_caisse_origine_unique')],
            },
        ),
    ]
