# Generated by Django 6.1.1 on 2026-09-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0004_generer_slugs_manquants'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_caisse', to='etablissement.etablissement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='etablissement.etablissement'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salaires', to='etablissement.etablissement'),
        ),
    ]
