# Generated by Django 6.1.1 on 2026-09-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0006_etablissement_code_devise_etablissement_pas_montant"),
        ("finances", "0003_rattacher_finances_existantes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixe", models.CharField(max_length=10)),
                ("annee", models.PositiveIntegerField()),
                ("dernier_numero", models.PositiveIntegerField(default=0)),
                (
                    "etablissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sequences_reference",
                        to="etablissement.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "séquence de référence",
                "verbose_name_plural": "séquences de référence",
                "unique_together": {("etablissement", "prefixe", "annee")},
            },
        ),
    ]
