# Generated by Django 6.1.1 on 2026-09-24 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0006_etablissement_code_devise_etablissement_pas_montant"),
        ("finances", "0004_sequencereference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salaire",
            unique_together={("employe", "periode")},
        ),
        migrations.AlterField(
            model_name="mouvementcaisse",
            name="reference",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="reference",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="salaire",
            name="reference",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paiement",
            unique_together={("etablissement", "reference")},
        ),
        migrations.AlterUniqueTogether(
            name="salaire",
            unique_together={("employe", "periode"), ("etablissement", "reference")},
        ),
        migrations.AddConstraint(
            model_name="mouvementcaisse",
            constraint=models.UniqueConstraint(
                fields=("etablissement", "reference"),
                name="mouvement_caisse_reference_unique_par_etablissement",
            ),
        ),
    ]
