# Generated by Django 6.1.1 on 2026-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0005_alter_salaire_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="tranche",
            field=models.CharField(
                choices=[
                    ("inscription", "Inscription"),
                    ("versement", "Versement de scolarité"),
                ],
                max_length=20,
            ),
        ),
    ]
