# Generated by Django 6.1.1 on 2026-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0006_alter_paiement_tranche"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="periodes_couvertes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Mois ou trimestres couverts par ce versement (ex. ['Janvier 2027', 'Février 2027']) - une famille peut régler n'importe quelle combinaison de mois, pas forcément consécutifs. Vide pour l'inscription ou un échéancier annuel.",
            ),
        ),
    ]
