# Generated by Django 6.1.1 on 2026-10-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0008_etablissement_taux_amo_employeur_and_more"),
        ("finances", "0007_paiement_periodes_couvertes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salaire",
            name="cotisation_amo_employeur",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaire",
            name="cotisation_amo_salarie",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaire",
            name="cotisation_inps_employeur",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaire",
            name="cotisation_inps_salarie",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaire",
            name="its",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Saisi manuellement - le barème officiel n'est pas calculé automatiquement par l'application.",
                verbose_name="ITS (impôt sur salaires)",
            ),
        ),
        migrations.AddField(
            model_name="salaire",
            name="salaire_brut",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salaire",
            name="montant",
            field=models.PositiveIntegerField(
                help_text="Montant net effectivement versé à l'employé."
            ),
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[("cdi", "CDI"), ("cdd", "CDD")], max_length=10
                    ),
                ),
                ("poste", models.CharField(max_length=150)),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide pour un CDI toujours en cours.",
                        null=True,
                    ),
                ),
                (
                    "salaire_base",
                    models.PositiveIntegerField(
                        help_text="Salaire brut mensuel de base."
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats",
                        to="etablissement.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrat",
                "verbose_name_plural": "contrats",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_conge",
                    models.CharField(
                        choices=[
                            ("paye", "Congé payé"),
                            ("maladie", "Congé maladie"),
                            ("maternite", "Congé maternité"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("refuse", "Refusé"),
                        ],
                        default="approuve",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_conge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_conge_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_conge",
                        to="etablissement.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "congé",
                "verbose_name_plural": "congés",
                "ordering": ["-date_debut"],
            },
        ),
    ]
