# Generated by Django 6.1.1 on 2026-09-21 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developpeur', 'Développeur'), ('fondateur', 'Fondateur'), ('administrateur_general', 'Administrateur général'), ('directeur_1er_cycle', 'Directeur du 1er cycle'), ('directeur_2eme_cycle', 'Directeur du 2ème cycle'), ('super_administrateur', 'Super administrateur'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('responsable_pedagogique', 'Responsable pédagogique'), ('bibliothecaire', 'Bibliothécaire'), ('personnel', 'Personnel (générique)'), ('enseignant', 'Enseignant'), ('parent', 'Parent'), ('eleve', 'Élève')], max_length=40)),
                ('module', models.CharField(choices=[('classes', 'Classes'), ('eleves', 'Élèves'), ('enseignants', 'Enseignants'), ('emploi_du_temps', 'Emploi du temps'), ('suivi_des_cours', 'Suivi des cours'), ('notes_bulletins', 'Notes et bulletins'), ('absences', 'Absences'), ('finances', 'Finances'), ('caisse', 'Caisse'), ('salaires', 'Salaires'), ('tests_de_niveau', 'Tests de niveau'), ('bibliotheque', 'Bibliothèque'), ('communication', 'Communication'), ('statistiques', 'Statistiques'), ('assistant', 'Assistant'), ('espace_developpeur', 'Espace développeur')], max_length=40)),
                ('autorise', models.BooleanField(default=False)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_matrice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'règle de la matrice de permissions',
                'verbose_name_plural': 'matrice de permissions',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
