# Generated by Django 6.1.1 on 2026-09-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0004_generer_slugs_manquants'),
        ('permissions_matrix', '0004_correction_suivi_cours_enseignant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionmatrix',
            options={'ordering': ['etablissement', 'role', 'module'], 'verbose_name': 'règle de la matrice de permissions', 'verbose_name_plural': 'matrice de permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='permissionmatrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permissionmatrix',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrice_permissions', to='etablissement.etablissement'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionmatrix',
            unique_together={('etablissement', 'role', 'module')},
        ),
    ]
